//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch1FlyoutPageModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ch1FlyoutPageModel.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Physical Activity.
        /// </summary>
        public static string ActivityRecognition {
            get {
                return ResourceManager.GetString("ActivityRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect user&apos;s physical activity via device sensors.
        /// </summary>
        public static string ActivityRecognitionDescription {
            get {
                return ResourceManager.GetString("ActivityRecognitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to pump iron.
        /// </summary>
        public static string ActivityRecognitionRationale {
            get {
                return ResourceManager.GetString("ActivityRecognitionRationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Camera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Camera.
        /// </summary>
        public static string CameraDescription {
            get {
                return ResourceManager.GetString("CameraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need pics to show our gainz.
        /// </summary>
        public static string CameraRationale {
            get {
                return ResourceManager.GetString("CameraRationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Background Location.
        /// </summary>
        public static string LocationAlwaysAllow {
            get {
                return ResourceManager.GetString("LocationAlwaysAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location access, even when app in background.
        /// </summary>
        public static string LocationAlwaysAllowDescription {
            get {
                return ResourceManager.GetString("LocationAlwaysAllowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need Wi-Fi permission, which can be used to determine location.
        /// </summary>
        public static string LocationAlwaysAllowRationale {
            get {
                return ResourceManager.GetString("LocationAlwaysAllowRationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Location while in use.
        /// </summary>
        public static string LocationOnlyForeground {
            get {
                return ResourceManager.GetString("LocationOnlyForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
    }
}
