//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch1FlyoutPageModel {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ch1FlyoutPageModel.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        public static string LocationAlwaysAllow {
            get {
                return ResourceManager.GetString("LocationAlwaysAllow", resourceCulture);
            }
        }
        
        public static string LocationOnlyForeground {
            get {
                return ResourceManager.GetString("LocationOnlyForeground", resourceCulture);
            }
        }
        
        public static string ActivityRecognition {
            get {
                return ResourceManager.GetString("ActivityRecognition", resourceCulture);
            }
        }
        
        public static string LocationAlwaysAllowDescription {
            get {
                return ResourceManager.GetString("LocationAlwaysAllowDescription", resourceCulture);
            }
        }
        
        public static string LocationAlwaysAllowRationale {
            get {
                return ResourceManager.GetString("LocationAlwaysAllowRationale", resourceCulture);
            }
        }
        
        public static string ActivityRecognitionDescription {
            get {
                return ResourceManager.GetString("ActivityRecognitionDescription", resourceCulture);
            }
        }
        
        public static string ActivityRecognitionRationale {
            get {
                return ResourceManager.GetString("ActivityRecognitionRationale", resourceCulture);
            }
        }
        
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        public static string CameraDescription {
            get {
                return ResourceManager.GetString("CameraDescription", resourceCulture);
            }
        }
        
        public static string CameraRationale {
            get {
                return ResourceManager.GetString("CameraRationale", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string LabelPermissionName {
            get {
                return ResourceManager.GetString("LabelPermissionName", resourceCulture);
            }
        }
        
        public static string LabelPermissionDescription {
            get {
                return ResourceManager.GetString("LabelPermissionDescription", resourceCulture);
            }
        }
        
        public static string LabelPermissionRationale {
            get {
                return ResourceManager.GetString("LabelPermissionRationale", resourceCulture);
            }
        }
        
        public static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        public static string TitleSettingsPage {
            get {
                return ResourceManager.GetString("TitleSettingsPage", resourceCulture);
            }
        }
        
        public static string TitlePermissionsPage {
            get {
                return ResourceManager.GetString("TitlePermissionsPage", resourceCulture);
            }
        }
        
        public static string TitleListPage {
            get {
                return ResourceManager.GetString("TitleListPage", resourceCulture);
            }
        }
        
        public static string LabelListResults {
            get {
                return ResourceManager.GetString("LabelListResults", resourceCulture);
            }
        }
        
        public static string BluetoothPermissionName {
            get {
                return ResourceManager.GetString("BluetoothPermissionName", resourceCulture);
            }
        }
        
        public static string BluetoothPermissionDescription {
            get {
                return ResourceManager.GetString("BluetoothPermissionDescription", resourceCulture);
            }
        }
        
        public static string BluetoothPermissionRationale {
            get {
                return ResourceManager.GetString("BluetoothPermissionRationale", resourceCulture);
            }
        }
        
        public static string ToastNumberOfRecordsReturned {
            get {
                return ResourceManager.GetString("ToastNumberOfRecordsReturned", resourceCulture);
            }
        }
        
        public static string ToastLifecycleOnStart {
            get {
                return ResourceManager.GetString("ToastLifecycleOnStart", resourceCulture);
            }
        }
        
        public static string ToastLifecycleOnSleep {
            get {
                return ResourceManager.GetString("ToastLifecycleOnSleep", resourceCulture);
            }
        }
        
        public static string ToastLifecycleOnResume {
            get {
                return ResourceManager.GetString("ToastLifecycleOnResume", resourceCulture);
            }
        }
        
        public static string PermissionStatus {
            get {
                return ResourceManager.GetString("PermissionStatus", resourceCulture);
            }
        }
        
        public static string BluetoothStatus {
            get {
                return ResourceManager.GetString("BluetoothStatus", resourceCulture);
            }
        }
        
        public static string LocationStatus {
            get {
                return ResourceManager.GetString("LocationStatus", resourceCulture);
            }
        }
        
        public static string NetworkStatus {
            get {
                return ResourceManager.GetString("NetworkStatus", resourceCulture);
            }
        }
        
        public static string TitleNotificationPage {
            get {
                return ResourceManager.GetString("TitleNotificationPage", resourceCulture);
            }
        }
        
        public static string SetAlarm {
            get {
                return ResourceManager.GetString("SetAlarm", resourceCulture);
            }
        }
        
        public static string ToastLifecycleOnPause {
            get {
                return ResourceManager.GetString("ToastLifecycleOnPause", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string TitleAppTitle {
            get {
                return ResourceManager.GetString("TitleAppTitle", resourceCulture);
            }
        }
        
        public static string TitleBluetoothPage {
            get {
                return ResourceManager.GetString("TitleBluetoothPage", resourceCulture);
            }
        }
        
        public static string ToastPermissionGranted {
            get {
                return ResourceManager.GetString("ToastPermissionGranted", resourceCulture);
            }
        }
    }
}
